/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Box: typeof import('./src/components/Box.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    Map: typeof import('./src/components/Map.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Target: typeof import('./src/components/Target.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}
